#!/bin/sh

set -f
exec 2>/dev/null

w=$2 h=$3 x=$4 y=$5

draw() {
	printf '{"action":"add","identifier":"preview","x":%d,"y":%d,"width":%d,"height":%d,"scaler":"contain","path":"%s"}\n' \
		"$x" "$y" "$w" "$h" "$1" >"$FIFO_UEBERZUG"
	exit 1
}

case $1 in
	*.jpg|*.jpeg|*.png|*.bmp|*.webp|*.gif|\
	*.JPG|*.JPEG|*.PNG|*.BMP|*.WEBP|*.GIF)
	draw "$1"
esac

file=$1

needs_update() { test ! -f "$1" || test "$file" -nt "$1" ; }
c() { CACHE=$XDG_CACHE_HOME/lf/`IFS=/; set $file; IFS=_; printf %s "$*"` ;}

case `file -Lb --mime-type -- "$1"` in
	image/avif|image/x-xcf|image/svg+xml) c;needs_update "$CACHE.jpg" && magick "$1[0]" "$CACHE.jpg"; draw "$CACHE.jpg" ;;
	image/*) draw "$1" ;;
	text/troff) COLUMNS="$w" man "$1" | col -b; exit ;;
	text/*|*/xml|application/*json) exec cat "$1" ;;
	audio/*|application/octet-stream) mediainfo "$1" && exit ;;
	video/*) c;needs_update "$CACHE.jpg" && ffmpegthumbnailer -i "$1" -o "$CACHE.jpg" -s 0; draw "$CACHE.jpg" ;;
	*/pdf) c;needs_update "$CACHE.jpg" && pdftoppm -f 1 -singlefile -jpeg "$1" "$CACHE"; draw "$CACHE.jpg" ;;
	application/*zip*|application/*tar|application/x-xz|application/x-7z-compressed|application/x-rar) exec bsdtar -tf "$1"
esac
file -Lb -- "$1" | fold -s -w "$w"
