#!/bin/sh
setbg &
status &
xset r rate 300 50
picom -b
redshift -P -O 3500
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
dunst &
unclutter &
mpd &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
