#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

# Statusbar
while true; do
  ram_usage=$(free | awk '/Mem/{printf("   RAM %.2f%"), $3/$2*100}')
  cpu_temp=$(echo "TEMP $(sed 's/000$/°C/' /sys/class/thermal/thermal_zone0/temp)")
  time_date=$(date "+%d %b (%a), %R   ")

  output="$ram_usage | $cpu_temp | $time_date"
  xsetroot -name "$output"

  sleep 10
done

# Activate dbus variables
dbus-update-activation-environment --all
dbus-launch ssh-agent dwm
