#!/bin/sh
config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/firefox"
t="/tmp/f$$"
trap 'rm -f $t' EXIT
curl -sL -o $t "https://raw.githubusercontent.com/yokoffing/Betterfox/refs/heads/main/user.js"
cat "$config_dir/custom.js" $t > "$config_dir/user.js"
