#!/bin/sh

echo "Stage 1: Removing cache..."
paccache -rvk0

echo "Stage 2: Removing unused packages..."
orphans=$(pacman -Qdtq); [ -z "$orphans" ] && echo "There are no orphaned packages" || pacman -Rns "$orphans"

echo "Stage 3: Detecting more unneeded packages..."
pacman -Qqd | pacman -Rsu --print -
