#!/bin/sh
while read -r file
do
        case "$1" in
        "w") setbg "$file" & ;;
        "s")
		dest=$(sed -e 's/\s*#.*//' -e '/^$/d' -e 's/^\S*\s*//' "${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs" | dmenu -l 15 -i -p "Copy to where?" | sed "s|~|$HOME|g"); dest=$(eval echo "$dest")
		[ ! -d "$dest" ] && notify-send "$dest is not a directory" && exit
		safe cp "$file" "$dest" && notify-send -i "$(readlink -f "$file")" "$file copied to $dest" &
		;;
        "c")
		safe cp "$file" "$HOME/Pictures" && notify-send -i "$(readlink -f "$file")" "Copied to Pictures" &
		;;
        "m")
		dest=$(sed -e 's/\s*#.*//' -e '/^$/d' -e 's/^\S*\s*//' "${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs" | dmenu -l 15 -i -p "Move to where?" | sed "s|~|$HOME|g"); dest=$(eval echo "$dest")
		[ ! -d "$dest" ] && notify-send "$dest is not a directory" && exit
		safe mv "$file" "$dest" && notify-send -i "$(readlink -f "$file")" "$file moved to $dest" &
		;;
	"r")
		magick -rotate 90 "$file" "$file" ;;
	"R")
		magick -rotate -90 "$file" "$file" ;;
	"f")
		magick -flop "$file" "$file" ;;
	"y")
		printf "%s" "$file" | tr -d '\n' | xclip -selection clipboard &&
		notify-send "$file copied to clipboard" & ;;
	"Y")
		readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
			notify-send "$(readlink -f "$file") copied to clipboard" & ;;
	"d")
		[ "$(printf "Yes\\nNo" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
	"g")	setsid -f gimp "$file" ;;
	"i")	notify-send "File information" "$(mediainfo "$file" | sed "s/[ ]\+:/:/g;s/: /: <b>/;s/$/<\/b>/" | grep "<b>")" ;;
        esac
done
