#!/bin/sh
setbg &
status &
xset r rate 300 50
xrdb $XDG_CONFIG_HOME/x11/xresources
unclutter &

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

exec dwm
