#!/bin/sh

echo Removing cache...
paccache -rvk0

echo Detecting more unneeded packages...
[ "`pacman -Qdtq`" ] && echo Orphaned packages found
[ "`pacman -Qqd | pacman -Rsu --print -`" ] && echo Optional packages found
