#!/bin/sh

echo Removing cache...
paccache -rvk0

echo Detecting more unneeded packages...
[ "`pacman -Qdtq`" ] && echo Orphaned packages found

case `pacman -Qqd | pacman -Rsu --print -` in
*'there is nothing'*)
	;;
*)
	echo Optional packages found
esac
